services:
  nginx:
    image: nginx:latest
    container_name: nginx
    extra_hosts:
      - "host.docker.internal:host-gateway"
    ports:
      - 80:80
    volumes:
      - ./docker/nginx:/etc/nginx/conf.d
  postgres:
    image: postgres:latest
    environment:
      TZ: Asia/Tokyo
      POSTGRES_DB: dev
      POSTGRES_USER: postgres
      POSTGRES_PASSWORD: password
      POSTGRES_INITDB_ARGS: "--encoding=UTF-8 --locale=C"
    ports:
      - 5432:5432